services:
  demo: &demo
    build:
      context: .
      dockerfile: Dockerfile
    container_name: es_demo
    env_file:
      - .env
    volumes:
      - ./:/app
    command: pdm run python
    stdin_open: true
    tty: true
  bash:
    <<: *demo
    command: bash
  download:
    <<: *demo
    command: pdm run python -m demo.download
  ingest:
    <<: *demo
    command: pdm run python -m demo.ingest