services:
  demo: &demo
    build:
      context: .
      dockerfile: Dockerfile
    container_name: es_demo
    env_file:
      - .env
    volumes:
      - ./:/app
    command: pdm run python
  bash:
    <<: *demo
    command: bash